# Generated by Django 5.1.1 on 2024-09-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_post", "0001_add_post_model"),
        ("core_user", "0003_add_post_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_liked",
            field=models.ManyToManyField(related_name="liked_by", to="core_post.post"),
        ),
    ]
